name: ucost_mobile_app
description: "UCOST Discovery Hub Mobile Application - World Class Museum Management System with Local-First P2P Sync"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI
  cupertino_icons: ^1.0.8
  
  # Network and API
  http: ^1.4.0
  connectivity_plus: ^5.0.2
  
  # Storage and File Management
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  path: ^1.9.0
  
  # State Management
  provider: ^6.1.5
  
  # Local Database
  sqflite: ^2.3.3+1
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.18.1
  
  # Image handling
  image_picker: ^1.1.2
  image: ^4.1.7
  
  # Network discovery
  multicast_dns: ^0.3.0+1
  network_info_plus: ^4.1.0+1
  
  # QR Code (simplified)
  qr_flutter: ^4.1.0
  
  # Charts and visualization
  fl_chart: ^0.69.0
  
  # Local notifications
  flutter_local_notifications: ^17.2.2
  
  # Permission handling
  permission_handler: ^11.3.1
  
  # File compression
  archive: ^3.4.10
  
  # JSON handling
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/ 