import '../models/exhibit.dart';

class MockDataService {
  static List<Exhibit> getMockExhibits() {
    return [
      Exhibit(
        id: '1',
        name: 'Quantum Physics Lab',
        description: 'Experience the fascinating world of quantum mechanics through interactive experiments. Learn about superposition, entanglement, and wave-particle duality with hands-on demonstrations that make complex physics concepts accessible to everyone.',
        category: 'science',
        location: 'ground_floor',
        imagePath: 'assets/images/quantum_lab.jpg',
        images: [
          'assets/images/quantum_lab_1.jpg',
          'assets/images/quantum_lab_2.jpg',
        ],
        metadata: {
          'accessible': true,
          'minAge': 10,
          'interactive': true,
        },
        tags: ['physics', 'quantum', 'interactive', 'experiment'],
        rating: 4.8,
        viewCount: 1250,
        isInteractive: true,
        isPopular: true,
        isNew: false,
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
        updatedAt: DateTime.now().subtract(const Duration(days: 5)),
        audioGuide: 'assets/audio/quantum_lab.mp3',
        videoUrl: 'https://example.com/quantum_lab_video.mp4',
        coordinates: {'x': 100, 'y': 150},
        difficulty: 'intermediate',
        estimatedDuration: 15,
        relatedExhibits: ['2', '3'],
      ),
      
      Exhibit(
        id: '2',
        name: 'Artificial Intelligence Hub',
        description: 'Discover the cutting-edge world of AI and machine learning. Interact with neural networks, test computer vision systems, and learn how artificial intelligence is transforming our daily lives.',
        category: 'technology',
        location: 'first_floor',
        imagePath: 'assets/images/ai_hub.jpg',
        images: [
          'assets/images/ai_hub_1.jpg',
          'assets/images/ai_hub_2.jpg',
        ],
        metadata: {
          'accessible': true,
          'minAge': 12,
          'interactive': true,
        },
        tags: ['AI', 'machine learning', 'neural networks', 'computer vision'],
        rating: 4.9,
        viewCount: 2100,
        isInteractive: true,
        isPopular: true,
        isNew: true,
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
        updatedAt: DateTime.now().subtract(const Duration(days: 2)),
        audioGuide: 'assets/audio/ai_hub.mp3',
        videoUrl: 'https://example.com/ai_hub_video.mp4',
        coordinates: {'x': 200, 'y': 100},
        difficulty: 'advanced',
        estimatedDuration: 20,
        relatedExhibits: ['1', '4'],
      ),
      
      Exhibit(
        id: '3',
        name: 'Ancient Civilizations Gallery',
        description: 'Journey through time and explore the rich history of ancient civilizations. From Egyptian pyramids to Roman architecture, discover the engineering marvels and cultural achievements that shaped human history.',
        category: 'history',
        location: 'ground_floor',
        imagePath: 'assets/images/ancient_civilizations.jpg',
        images: [
          'assets/images/ancient_civilizations_1.jpg',
          'assets/images/ancient_civilizations_2.jpg',
        ],
        metadata: {
          'accessible': true,
          'minAge': 8,
          'interactive': false,
        },
        tags: ['history', 'ancient', 'civilizations', 'archaeology'],
        rating: 4.6,
        viewCount: 980,
        isInteractive: false,
        isPopular: false,
        isNew: false,
        createdAt: DateTime.now().subtract(const Duration(days: 60)),
        updatedAt: DateTime.now().subtract(const Duration(days: 10)),
        audioGuide: 'assets/audio/ancient_civilizations.mp3',
        coordinates: {'x': 150, 'y': 200},
        difficulty: 'beginner',
        estimatedDuration: 25,
        relatedExhibits: ['1', '5'],
      ),
      
      Exhibit(
        id: '4',
        name: 'Digital Art Studio',
        description: 'Create stunning digital artwork using the latest technology. Experiment with digital painting, 3D modeling, and virtual reality art creation tools.',
        category: 'art',
        location: 'second_floor',
        imagePath: 'assets/images/digital_art_studio.jpg',
        images: [
          'assets/images/digital_art_studio_1.jpg',
          'assets/images/digital_art_studio_2.jpg',
        ],
        metadata: {
          'accessible': true,
          'minAge': 13,
          'interactive': true,
        },
        tags: ['art', 'digital', '3D modeling', 'VR', 'creative'],
        rating: 4.7,
        viewCount: 750,
        isInteractive: true,
        isPopular: false,
        isNew: true,
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
        updatedAt: DateTime.now().subtract(const Duration(days: 1)),
        audioGuide: 'assets/audio/digital_art_studio.mp3',
        coordinates: {'x': 300, 'y': 250},
        difficulty: 'intermediate',
        estimatedDuration: 30,
        relatedExhibits: ['2', '6'],
      ),
      
      Exhibit(
        id: '5',
        name: 'Ecosystem Discovery Center',
        description: 'Explore diverse ecosystems and learn about environmental conservation. Walk through recreated habitats and discover the interconnected web of life that sustains our planet.',
        category: 'nature',
        location: 'outdoor',
        imagePath: 'assets/images/ecosystem_center.jpg',
        images: [
          'assets/images/ecosystem_center_1.jpg',
          'assets/images/ecosystem_center_2.jpg',
        ],
        metadata: {
          'accessible': true,
          'minAge': 5,
          'interactive': true,
        },
        tags: ['nature', 'ecosystem', 'environment', 'conservation'],
        rating: 4.5,
        viewCount: 650,
        isInteractive: true,
        isPopular: false,
        isNew: false,
        createdAt: DateTime.now().subtract(const Duration(days: 45)),
        updatedAt: DateTime.now().subtract(const Duration(days: 8)),
        audioGuide: 'assets/audio/ecosystem_center.mp3',
        coordinates: {'x': 400, 'y': 300},
        difficulty: 'beginner',
        estimatedDuration: 35,
        relatedExhibits: ['3', '7'],
      ),
      
      Exhibit(
        id: '6',
        name: 'Space Exploration Station',
        description: 'Embark on a journey through the cosmos. Learn about space missions, explore planetary models, and experience the wonders of our solar system and beyond.',
        category: 'space',
        location: 'second_floor',
        imagePath: 'assets/images/space_station.jpg',
        images: [
          'assets/images/space_station_1.jpg',
          'assets/images/space_station_2.jpg',
        ],
        metadata: {
          'accessible': true,
          'minAge': 10,
          'interactive': true,
        },
        tags: ['space', 'astronomy', 'planets', 'solar system', 'exploration'],
        rating: 4.9,
        viewCount: 1800,
        isInteractive: true,
        isPopular: true,
        isNew: false,
        createdAt: DateTime.now().subtract(const Duration(days: 40)),
        updatedAt: DateTime.now().subtract(const Duration(days: 3)),
        audioGuide: 'assets/audio/space_station.mp3',
        videoUrl: 'https://example.com/space_station_video.mp4',
        coordinates: {'x': 350, 'y': 180},
        difficulty: 'intermediate',
        estimatedDuration: 20,
        relatedExhibits: ['4', '8'],
      ),
      
      Exhibit(
        id: '7',
        name: 'Renewable Energy Lab',
        description: 'Discover sustainable energy solutions for the future. Learn about solar power, wind energy, and other renewable technologies through hands-on experiments.',
        category: 'technology',
        location: 'basement',
        imagePath: 'assets/images/renewable_energy.jpg',
        images: [
          'assets/images/renewable_energy_1.jpg',
          'assets/images/renewable_energy_2.jpg',
        ],
        metadata: {
          'accessible': true,
          'minAge': 12,
          'interactive': true,
        },
        tags: ['energy', 'renewable', 'solar', 'wind', 'sustainability'],
        rating: 4.4,
        viewCount: 520,
        isInteractive: true,
        isPopular: false,
        isNew: false,
        createdAt: DateTime.now().subtract(const Duration(days: 70)),
        updatedAt: DateTime.now().subtract(const Duration(days: 15)),
        audioGuide: 'assets/audio/renewable_energy.mp3',
        coordinates: {'x': 250, 'y': 400},
        difficulty: 'intermediate',
        estimatedDuration: 18,
        relatedExhibits: ['5', '9'],
      ),
      
      Exhibit(
        id: '8',
        name: 'Marine Biology Center',
        description: 'Dive into the fascinating world of marine life. Explore ocean ecosystems, learn about marine conservation, and discover the incredible diversity of sea creatures.',
        category: 'nature',
        location: 'ground_floor',
        imagePath: 'assets/images/marine_biology.jpg',
        images: [
          'assets/images/marine_biology_1.jpg',
          'assets/images/marine_biology_2.jpg',
        ],
        metadata: {
          'accessible': true,
          'minAge': 6,
          'interactive': true,
        },
        tags: ['marine', 'ocean', 'biology', 'conservation', 'sea life'],
        rating: 4.6,
        viewCount: 890,
        isInteractive: true,
        isPopular: false,
        isNew: false,
        createdAt: DateTime.now().subtract(const Duration(days: 55)),
        updatedAt: DateTime.now().subtract(const Duration(days: 7)),
        audioGuide: 'assets/audio/marine_biology.mp3',
        coordinates: {'x': 180, 'y': 350},
        difficulty: 'beginner',
        estimatedDuration: 22,
        relatedExhibits: ['6', '10'],
      ),
      
      Exhibit(
        id: '9',
        name: 'Robotics Workshop',
        description: 'Build and program robots in this hands-on workshop. Learn about automation, artificial intelligence, and the future of robotics in our daily lives.',
        category: 'technology',
        location: 'first_floor',
        imagePath: 'assets/images/robotics_workshop.jpg',
        images: [
          'assets/images/robotics_workshop_1.jpg',
          'assets/images/robotics_workshop_2.jpg',
        ],
        metadata: {
          'accessible': true,
          'minAge': 14,
          'interactive': true,
        },
        tags: ['robotics', 'automation', 'programming', 'engineering'],
        rating: 4.8,
        viewCount: 1100,
        isInteractive: true,
        isPopular: true,
        isNew: false,
        createdAt: DateTime.now().subtract(const Duration(days: 35)),
        updatedAt: DateTime.now().subtract(const Duration(days: 4)),
        audioGuide: 'assets/audio/robotics_workshop.mp3',
        videoUrl: 'https://example.com/robotics_workshop_video.mp4',
        coordinates: {'x': 280, 'y': 120},
        difficulty: 'advanced',
        estimatedDuration: 25,
        relatedExhibits: ['7', '11'],
      ),
      
      Exhibit(
        id: '10',
        name: 'Climate Change Exhibition',
        description: 'Understand the science behind climate change and explore solutions for a sustainable future. Interactive displays show the impact of human activities on our planet.',
        category: 'science',
        location: 'ground_floor',
        imagePath: 'assets/images/climate_change.jpg',
        images: [
          'assets/images/climate_change_1.jpg',
          'assets/images/climate_change_2.jpg',
        ],
        metadata: {
          'accessible': true,
          'minAge': 10,
          'interactive': true,
        },
        tags: ['climate', 'environment', 'sustainability', 'science'],
        rating: 4.7,
        viewCount: 950,
        isInteractive: true,
        isPopular: false,
        isNew: true,
        createdAt: DateTime.now().subtract(const Duration(days: 25)),
        updatedAt: DateTime.now().subtract(const Duration(days: 2)),
        audioGuide: 'assets/audio/climate_change.mp3',
        coordinates: {'x': 120, 'y': 280},
        difficulty: 'intermediate',
        estimatedDuration: 20,
        relatedExhibits: ['8', '12'],
      ),
    ];
  }
} 